### ISSUE TITLE
A5_정보보호포털_A5B4_정보보호포털 오류(로그인 및 결재 신청) (웅현님)

### ISSUE THREAD

**Issue by kimjimann** [kimjimann/chatbot#12]

**Comment by bwh0110** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152960756/b3e241c9-1b68-471b-9fcc-72b767fc2411)
포털 로그인 실패 이미지

**Comment by bwh0110** [comment]
<img width="1415" alt="MicrosoftTeams-image (61) (1)" src="https://github.com/kimjimann/chatbot/assets/152960756/0b511a17-507e-411a-be36-6ca5b44aeb12">

**Comment by bwh0110** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152960756/f3cf0205-fee4-4165-8339-bb00d9e52033)
포털 오류페이지 편집본1
