### ISSUE TITLE
A1B1_오피스키퍼_A1B1C2_MAC OS 이미지 모음 (태민님)

### ISSUE THREAD

**Issue by kimjimann** [kimjimann/chatbot#3]

**Comment by jtm0608** [comment]
<img width="209" alt="image" src="https://github.com/kimjimann/chatbot/assets/152952899/3bdfb3d2-2afe-4fa4-9242-3d9094a1664e">

**Comment by jtm0608** [comment]
<img width="209" alt="image" src="https://github.com/kimjimann/chatbot/assets/152952899/1525f0cc-b060-4066-b5fe-6ba7ba806632">

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/7f3323ef-d444-487f-bfaa-c004ec74fed0)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/4040d57a-fb0d-4d53-9a6c-11fb98c98ee2)

**Comment by jtm0608** [comment]
<img width="343" alt="image" src="https://github.com/kimjimann/chatbot/assets/152952899/db2dd3e2-8f6f-45c8-9c0a-2fa0b081d5f8">

**Comment by jtm0608** [comment]
<img width="340" alt="image" src="https://github.com/kimjimann/chatbot/assets/152952899/aef40724-c202-4e97-b67e-8ddab0d04ab4">

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/e6acb6de-784d-4f39-979f-f7eb92ef821a)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/684fa7c2-a6a1-4ed8-a39f-482fcd776fe1)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/f434491b-34b0-4a89-8d79-b56225b0a939)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/8d5effe9-3a12-4a06-b924-d5a7c16e3939)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/2a4a3e41-0445-46d2-a56c-2965436690cb)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/dc442d37-1ba6-4afe-979f-7ac17bc967a5)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/b2b220fe-7ec5-4473-ae82-dcc2eb548f8e)

**Comment by jtm0608** [comment]
![image](https://github.com/kimjimann/chatbot/assets/152952899/9cace5a7-2997-4048-9341-a828f37f7304)
