### ISSUE TITLE
A1B3_Hiware 이미지 모음 (장훈님)

### ISSUE THREAD

**Issue by kimjimann** [kimjimann/chatbot#5]

**Comment by MunJH** [comment]
A1B2C2_서버 접근권한 신청

![image](https://github.com/kimjimann/chatbot/assets/29170060/ea3c09fb-979c-4633-b3f6-90ac0feb4871)

**Comment by MunJH** [comment]
A1B3C4_서버 접속 오류 문의

![image](https://github.com/kimjimann/chatbot/assets/29170060/fc39133f-82c5-4483-b771-0dd6963b3167)

**Comment by MunJH** [comment]
A1B3C5_MAC OS에서 HIWARE 사용 오류 문의

![image](https://github.com/kimjimann/chatbot/assets/29170060/5b45a554-64be-4cd9-a037-b316ae6584bc)
![image](https://github.com/kimjimann/chatbot/assets/29170060/09f01019-9cfe-49e2-8126-0884a7832451)

**Comment by MunJH** [comment]
계정신청

![image](https://github.com/kimjimann/chatbot/assets/29170060/7cb6f71b-d60b-4664-b62c-4b0e544585f7)

**Comment by MunJH** [comment]
기타양식신청
![image](https://github.com/kimjimann/chatbot/assets/29170060/6c39bc30-9c68-4073-9304-2c9e31744273)
