### ISSUE TITLE
A2_네트워크_A2B1_NAC 이미지 모음 (웅현님)

### ISSUE THREAD

**Issue by kimjimann** [kimjimann/chatbot#9]

**Comment by bwh0110** [comment]
내상태 확인
![image](https://github.com/kimjimann/chatbot/assets/152960756/48a885b5-3a3c-46b9-9fee-70b44ba3a40c)

**Comment by bwh0110** [comment]
캡쳐화면
![image](https://github.com/kimjimann/chatbot/assets/152960756/54c6ea56-22be-4c79-8636-32b3b7e88241)
